### ISSUE TITLE
Getting Platform Not Supported Error

### ISSUE THREAD

**Issue by Derrick-Tan-Aquametro** [ektrah/nsec#76]
I am in windows 10.

All the libsodium.dll files is here:
![image](https://github.com/ektrah/nsec/assets/138413602/183d244d-a040-4fb6-9a83-db45ac8e0a2c)

But I am getting this error...
It is after build, does it affect by Virtual Machine?
I don't think so right...

![image](https://github.com/ektrah/nsec/assets/138413602/11ed1512-874b-4abd-b62b-0a9c6025a64e)

**Comment by mimeister** [comment]
I seem to have the the same problem with my .NET 6 WPF applications.
When running on a physical Win10 machine, everything is fine, but if I run the applications inside of a Win10 VirtualBox VM or the Windows Sandbox a `PlatformNotSupportedException` is thrown as soon as any NSec functionality is used:
```
2023-08-17 12:59:45.6827 ERROR System.Exception System.PlatformNotSupportedException: Could not initialize platform-specific components. NSec may not be supported on this platform. See https://nsec.rocks/docs/install for more information. 
EXCEPTION: System.PlatformNotSupportedException: Could not initialize platform-specific components. NSec may not be supported on this platform. See https://nsec.rocks/docs/install for more information.
 ---> System.DllNotFoundException: Unable to load DLL 'libsodium' or one of its dependencies: Das angegebene Modul wurde nicht gefunden. (0x8007007E)
   at Interop.Libsodium.sodium_library_version_major()
   at NSec.Cryptography.Sodium.InitializeCore()
   --- End of inner exception stack trace ---
   at NSec.Cryptography.Sodium.InitializeCore()
   at NSec.Cryptography.Algorithm..ctor()
   at NSec.Cryptography.HashAlgorithm..ctor(Int32 hashSize)
   at NSec.Cryptography.Blake2b..ctor(Int32 hashSize)
   at NSec.Cryptography.HashAlgorithm.get_Blake2b_256()
```

**Comment by mimeister** [comment]
Thanks, I had overlooked that. It works after installing that.

**Comment by samuel-lucas6** [comment]
It is quite easy to miss. @ektrah do you think it would be worth putting it in a highlighted Note section like the warning about nonce reuse for AEADs?

**Comment by ektrah** [comment]
I have reworked the page a bit in 0eb608dd6908f4ed5ba6446a3f6b7ecb04e799a2. I hope that makes it more clear 😸
